version: '3.8'

services:
  app:
    build: .
    container_name: video_downloader
    restart: always
    environment:
      - WORKERS=4
      - DOMAIN_NAME=localhost
      - REDIS_URL=redis://redis:6379/0
      - ROOT_PATH=/downloader
    ports:
      - "5001:8000"
    volumes:
      - ./temp:/app/temp
      - ./proxies.txt:/app/proxies.txt
      - ./cookies.txt:/app/cookies.txt
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3G

  redis:
    image: redis:alpine
    container_name: video_downloader_redis
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data:
